# Generated by Django 6.0.1 on 2026-02-06 19:51

from django.db import migrations


def set_existing_users_verified(apps, schema_editor):
    """Set all existing users as verified and active."""
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(email_verified=True, is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_alter_user_is_active'),
    ]

    operations = [
        migrations.RunPython(set_existing_users_verified, migrations.RunPython.noop),
    ]
