# Generated by Django 6.0.1 on 2026-02-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_set_existing_users_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False, help_text='Can create and manage blog posts and courses'),
        ),
    ]
