# Generated by Django 6.0.1 on 2026-01-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='course',
        ),
        migrations.RemoveField(
            model_name='post',
            name='order',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('tutorial', 'Tutorial'), ('article', 'Article')], default='tutorial', max_length=20),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
    ]
