# Generated by Django 6.0.1 on 2026-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL if this is republished content', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword to focus on for SEO', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for search engines (160 chars max, if empty will use excerpt)', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='og_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for Open Graph image', max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reading_time_override',
            field=models.PositiveIntegerField(blank=True, help_text='Manual reading time in minutes (if empty, will be calculated)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='schema_type',
            field=models.CharField(choices=[('Article', 'Article'), ('BlogPosting', 'Blog Post'), ('TechArticle', 'Technical Article'), ('Tutorial', 'Tutorial'), ('HowTo', 'How-To Guide')], default='BlogPosting', help_text='Schema.org type for structured data', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO optimized title (60 chars max, if empty will use main title)', max_length=60, null=True),
        ),
    ]
