# Generated by Django 6.0.1 on 2026-02-12 23:48

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=markdownx.models.MarkdownxField(help_text='Write in Markdown format - you can drag and drop images directly'),
        ),
    ]
