# Generated by Django 6.0.1 on 2026-04-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_downloads', models.IntegerField(default=0)),
                ('failed_downloads', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('instagram_downloads', models.IntegerField(default=0)),
                ('youtube_downloads', models.IntegerField(default=0)),
                ('twitter_downloads', models.IntegerField(default=0)),
                ('total_data_transferred', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Statistics',
                'verbose_name_plural': 'Bot Statistics',
                'db_table': 'bot_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram User ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram Username')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is Blocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'db_table': 'bot_telegram_users',
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, verbose_name='Media URL')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('unknown', 'Unknown')], max_length=20, verbose_name='Platform')),
                ('media_type', models.CharField(blank=True, choices=[('video', 'Video'), ('image', 'Image'), ('carousel', 'Carousel')], max_length=20, null=True, verbose_name='Media Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('download_duration', models.FloatField(blank=True, null=True, verbose_name='Download Duration (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='bot_app.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Download Request',
                'verbose_name_plural': 'Download Requests',
                'db_table': 'bot_download_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='bot_downloa_user_id_059f75_idx'), models.Index(fields=['status', '-created_at'], name='bot_downloa_status_fe3796_idx'), models.Index(fields=['platform', '-created_at'], name='bot_downloa_platfor_7eec8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='bot_app.telegramuser')),
            ],
            options={
                'verbose_name': 'Bot Log',
                'verbose_name_plural': 'Bot Logs',
                'db_table': 'bot_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', '-created_at'], name='bot_logs_level_738fdc_idx')],
            },
        ),
    ]
