# Generated by ChatGPT on 2026-01-15
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_post_price'),
        ('courses', '0002_courseenrollment_last_lesson'),
        ('services', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='courses.course')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='blog.post')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='basketitem',
            constraint=models.UniqueConstraint(condition=Q(('post__isnull', False)), fields=('user', 'post'), name='unique_post_basket_item_per_user'),
        ),
        migrations.AddConstraint(
            model_name='basketitem',
            constraint=models.UniqueConstraint(condition=Q(('course__isnull', False)), fields=('user', 'course'), name='unique_course_basket_item_per_user'),
        ),
        migrations.AddConstraint(
            model_name='basketitem',
            constraint=models.UniqueConstraint(condition=Q(('service__isnull', False)), fields=('user', 'service'), name='unique_service_basket_item_per_user'),
        ),
    ]