# Generated by Django 6.0.1 on 2026-01-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_invoice_orderitem_alter_basketitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coinbase_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coinbase_hosted_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='crypto_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='crypto_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='crypto_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
